# Generated by Django 2.0.5 on 2018-09-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20180924_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='number_of_product',
            field=models.IntegerField(default=1),
        ),
    ]
