# Generated by Django 2.0.5 on 2018-10-29 17:36

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20180924_1929'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cart',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
