# Generated by Django 2.0.5 on 2018-11-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20181029_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='number_of_product',
            field=models.IntegerField(default=0),
        ),
    ]
