# Generated by Django 2.0.5 on 2018-11-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20181114_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, db_index=True, to='cart.CartItem'),
        ),
    ]
