# Generated by Django 2.0.5 on 2018-07-02 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_active',
            new_name='status',
        ),
    ]
