# Generated by Django 2.0.5 on 2018-07-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180702_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='productinorder',
            old_name='numberOfProduct',
            new_name='number_of_product',
        ),
    ]
