# Generated by Django 2.0.5 on 2018-10-29 17:33

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20181024_1952'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
