# Generated by Django 3.0.3 on 2020-04-04 14:54

import builtins
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200319_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': [builtins.id]},
        ),
    ]
