# Generated by Django 2.0.5 on 2018-09-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180904_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
