# Generated by Django 2.0.5 on 2018-11-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20181113_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='create',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='update',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='create',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='update',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
