# Generated by Django 2.0.5 on 2018-12-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20181129_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=128, null=True),
        ),
    ]
